name: hydrated_bloc_integration
description: An extension to the bloc state management library which automatically persists and restores bloc states. Supports integration testing.
version: 0.0.1-rc2
repository: https://github.com/PROGrand/hydrated_bloc_integration
issue_tracker: https://github.com/PROGrand/hydrated_bloc_integration/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  hive: ^2.0.0
  meta: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  test: ^1.18.2
  build_runner: ^2.1.4
  collection: ^1.15.0
  crypto: ^3.0.0
  freezed_annotation: ^0.15.0
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
  json_annotation: ^4.3.0
  mocktail: ^0.2.0
  path: ^1.8.0
  uuid: ^3.0.0
