name: hydrated_bloc_integration
description: An extension to the bloc state management library which automatically persists and restores bloc states.
version: 9.0.0-rc1
repository: https://github.com/PROGrand/hydrated_bloc_integration
issue_tracker: https://github.com/PROGrand/hydrated_bloc_integration/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  hive: ^2.0.0
  meta: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  test: ^1.22.2
  build_runner: ^2.3.3
  collection: ^1.17.1
  crypto: ^3.0.2
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  mocktail: ^0.3.0
  path: ^1.8.3
  uuid: ^3.0.7
